### ISSUE TITLE
remote image scanner should read from the original registry for all image layers

### ISSUE THREAD

**Issue by partkyle** [defenseunicorns/uds-security-hub#153]
The remote scanner is reaching out to external registries, which is not correct because
1. the upstream could have changed since the package was built
2. the upstream might not exist in the case of a locally created image

Per #149, we should change the method in remote image scanner to use the rootfs method from the local scan.

**Comment by naveensrinivasan** [comment]
https://github.com/defenseunicorns/uds-software-factory/issues/63#issuecomment-2274288488
