### ISSUE TITLE
The scanner creates a large number of temporary files and leaves them behind

### ISSUE THREAD

**Issue by partkyle** [defenseunicorns/uds-security-hub#177]
There are a few places where we generate temporary files for scans and then we don't properly clean them up.

- https://github.com/search?q=repo%3Adefenseunicorns%2Fuds-security-hub%20os.MkdirTemp&type=code
- https://github.com/search?q=repo%3Adefenseunicorns%2Fuds-security-hub+os.CreateTemp&type=code

**Comment by naveensrinivasan** [comment]
This has been addressed.
