### ISSUE TITLE
Clean up Looker Studio (Views & Data)

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-security-hub#229]
# Clean up Looker Studio (Views & Data)

### Is your feature request related to a problem? Please describe

As a consumer of the Security Hub Looker data, I want to ensure that the information I'm viewing is truthful and up-to-date. This is crucial for maintaining confidence when presenting the data to potential customers and making informed decisions based on the dashboard.

### Describe the solution you'd like

- **Given** a person logs into Security Hub Looker Studio
- **When** they view any dashboard or report
- **Then** they should see accurate, verified, and up-to-date data

### Describe alternatives you've considered

- Delete looker Studio entirely and have consumers query the DBs to be manipulated and displayed (This option would require users to have more technical expertise and could potentially limit accessibility of the data)

### Additional context

[Slack Message](https://defense-unicorns.slack.com/archives/C0720S91762/p1725633127025909)
> With the increased interest in this data I want to make sure that we can stand behind what is in the looker studio or get rid of it entirely. @naveen @partkyle can we please take a look at the data being displayed to make sure that what is in there is true data. If we cannot trust any of the views I would like to remove them for now.  - Adam

**Comment by benjaminwilcox** [comment]
Per the convo yesterday, Looker Studio will be nuked.
