### ISSUE TITLE
Move to uds-security-hub GCP project

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-security-hub#262]
At the moment, all our instances are in Eddie's demo project within GCP. 

We have a dedicated project uds-security-hub.

Mover our DB to this new instance.

**Comment by adam-defenseunicorns** [comment]
If we are removing the Postgres requirement this may not be necessary.

**Comment by benjaminwilcox** [comment]
Per the convo yesterday, Looker Studio will be nuked.
